export const ACCESS_TOKEN = "ai_access_token";
export const LOGOUT_REQUIRED = "LOGOUT_REQUIRED";
export const LANGUAGE = "language";
export const SCREEN_SIZE = {
  MOBILE: 800,
  TABLET: 1023,
  DESKTOP: 1024,
};
export const BALANCE_TYPE = {
  DEPOSIT: "DEPOSIT",
  WITHDRAW: "WITHDRAW",
  TRANSFER: "TRANSFER",
  RECEIVED: "RECEIVED",
  COMMISSION_PACKAGE: "COMMISSION_PACKAGE",
  COMMISSION_INTEREST: "COMMISSION_INTEREST",
  BUY_PACKAGE: "BUY_PACKAGE",
  CLAIM: "CLAIM",
  INTEREST: "INTEREST",
};
export const REFUND = {
  SUCCESS: "SUCCESS",
  PENDING: "PENDING",
  BLOCK: "BLOCK",
};
